version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: php-fpm
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - postgres
            - redis

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        ports:
            - "80:80"  # или "8080:80", если порт 80 занят на хосте
        networks:
            - app-network
        depends_on:
            - php

    postgres:
        image: postgres:13
        container_name: postgres
        environment:
            POSTGRES_DB: bot_db
            POSTGRES_USER: bot_user
            POSTGRES_PASSWORD: bot_password
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    redis:
        image: redis:latest
        container_name: redis-cache
        restart: always
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
        driver: local
